INSERT INTO authors (name) values ("Barr, Nevada");
INSERT INTO authors (name) values ("Groen, Hendrik");
INSERT INTO authors (name) values ("Bach, Sebastian");
INSERT INTO authors (name) values ("Parks, Gordon");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Martin, George R.R.");
INSERT INTO authors (name) values ("Martin, George R.R.");
INSERT INTO authors (name) values ("Tremmel Wilcox, Annie");
INSERT INTO authors (name) values ("Harkness, Deborah");
INSERT INTO authors (name) values ("Exley, Frederick");
INSERT INTO authors (name) values ("Martin, George R.R.");
INSERT INTO authors (name) values ("Orchard, Sandra");
INSERT INTO authors (name) values ("Martin, George R.R.");
INSERT INTO authors (name) values ("Ernest J. Gaines");
INSERT INTO authors (name) values ("Bradlee, Ben");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Soni, Jimmy");
INSERT INTO authors (name) values ("Ford, Richard");
INSERT INTO authors (name) values ("Nanne, Lou");
INSERT INTO authors (name) values ("Nicholls, David");
INSERT INTO authors (name) values ("Lewycka, Marina");
INSERT INTO authors (name) values ("Trubek, Anne");
INSERT INTO authors (name) values ("Haddon, Mark");
INSERT INTO authors (name) values ("Martin, George R.R.");
INSERT INTO authors (name) values ("Hamilton, Laurell K.");
INSERT INTO authors (name) values ("Thomas, Abigail");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Popova, Maria");
INSERT INTO authors (name) values ("Egan, Jennifer");
INSERT INTO authors (name) values ("Child, Lee");
INSERT INTO authors (name) values ("Thoreau, Henry David");
INSERT INTO authors (name) values ("Cahill, Tim");
INSERT INTO authors (name) values ("Grahame-Smith, Seth");
INSERT INTO authors (name) values ("Kennedy, Donald");
INSERT INTO authors (name) values ("Trees, Andrew");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Hutchinson, Roger");
INSERT INTO authors (name) values ("Christian, Brian");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Gessen, Keith");
INSERT INTO authors (name) values ("Updike, John");
INSERT INTO authors (name) values ("Flynn, Vince");
INSERT INTO authors (name) values ("Gaiman, Neil");
INSERT INTO authors (name) values ("Strout, Elizabeth");
INSERT INTO authors (name) values ("Box, George E.P.");
INSERT INTO authors (name) values ("Hitchens, Christopher");
INSERT INTO authors (name) values ("Trussoni, Danielle");
INSERT INTO authors (name) values ("Trussoni, Danielle");
INSERT INTO authors (name) values ("Pollack, Nick");
INSERT INTO authors (name) values ("Strout, Elizabeth");
INSERT INTO authors (name) values ("Kent, Nick");
INSERT INTO authors (name) values ("Netz, Reviel");
INSERT INTO authors (name) values ("Handler, Chelsea");
INSERT INTO authors (name) values ("Vonnegut, Kurt");
INSERT INTO authors (name) values ("Smiley, Jane");
INSERT INTO authors (name) values ("Cerf, Bennett");
INSERT INTO authors (name) values ("McEwan, Ian");
INSERT INTO authors (name) values ("Rowell, Rainbow");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Wolff, Tobias");
INSERT INTO authors (name) values ("Kihn, Martin");
INSERT INTO authors (name) values ("Grogan, John");
INSERT INTO authors (name) values ("Flood, John");
INSERT INTO authors (name) values ("Adler, Joseph");
INSERT INTO authors (name) values ("McPherson, James M.");
INSERT INTO authors (name) values ("Martel, Yann");
INSERT INTO authors (name) values ("Benatar, Pat");
INSERT INTO authors (name) values ("Norris, Mary");
INSERT INTO authors (name) values ("Moriarty, Liane");
INSERT INTO authors (name) values ("Lamott, Anne");
INSERT INTO authors (name) values ("Rosengren, John");
INSERT INTO authors (name) values ("Ginsberg, Debra");
INSERT INTO authors (name) values ("Iles, Greg");
INSERT INTO authors (name) values ("Hamilton, Gabrielle");
INSERT INTO authors (name) values ("Roach, Mary");
INSERT INTO authors (name) values ("McMurtry, Larry");
INSERT INTO authors (name) values ("Russo, Richard");
INSERT INTO authors (name) values ("Ballard, Robert D.");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Sonneborn, Julia");
INSERT INTO authors (name) values ("Sawyer, Robert J.");
INSERT INTO authors (name) values ("Sendak, Maurice");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Sieve, Mark");
INSERT INTO authors (name) values ("Bitner, Jason");
INSERT INTO authors (name) values ("Anderson, Laurie Halse");
INSERT INTO authors (name) values ("Collins, Suzanne");
INSERT INTO authors (name) values ("Mayle, Peter");
INSERT INTO authors (name) values ("Krinsky, Natalie");
INSERT INTO authors (name) values ("Marquez, Gabriel Garcia");
INSERT INTO authors (name) values ("Benioff, David");
INSERT INTO authors (name) values ("Albertine, Viv");
INSERT INTO authors (name) values ("Mundy, Liza");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Perkins, John");
INSERT INTO authors (name) values ("Kafai, Yasmin B.");
INSERT INTO authors (name) values ("Neubauer, Alexander");
INSERT INTO authors (name) values ("Hintz, Martin");
INSERT INTO authors (name) values ("Preston, Richard");
INSERT INTO authors (name) values ("Stegner, Wallace");
INSERT INTO authors (name) values ("Kava, Alex");
INSERT INTO authors (name) values ("Crumley, James");
INSERT INTO authors (name) values ("Lustbader, Eric");
INSERT INTO authors (name) values ("Lupica, Mike");
INSERT INTO authors (name) values ("Harris, Charlaine");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Harris, Charlaine");
INSERT INTO authors (name) values ("Harris, Charlaine");
INSERT INTO authors (name) values ("Schumacher, Julie");
INSERT INTO authors (name) values ("Spence, Annie");
INSERT INTO authors (name) values ("Reay, Katherine");
INSERT INTO authors (name) values ("Kurkov, Andrey");
INSERT INTO authors (name) values ("Heller, Steven");
INSERT INTO authors (name) values ("Lindsay, Jeff");
INSERT INTO authors (name) values ("Lindsay, Jeff");
INSERT INTO authors (name) values ("Landau, Sidney I.");
INSERT INTO authors (name) values ("Child, Lee");
INSERT INTO authors (name) values ("Lowe, Jaime");
INSERT INTO authors (name) values ("Nahin, Paul J.");
INSERT INTO authors (name) values ("Gibson, William");
INSERT INTO authors (name) values ("Quinn, Spencer");
INSERT INTO authors (name) values ("Myrie, Russell");
INSERT INTO authors (name) values ("Dunn, Jancee");
INSERT INTO authors (name) values ("Lindsay, Jeff");
INSERT INTO authors (name) values ("Orwell, George");
INSERT INTO authors (name) values ("Morgan, Judith");
INSERT INTO authors (name) values ("Crichton, Michael");
INSERT INTO authors (name) values ("Rosenberg, Scott");
INSERT INTO authors (name) values ("Dreyer, Benjamin");
INSERT INTO authors (name) values ("Brant, John");
INSERT INTO authors (name) values ("Foer, Jonathan Safran");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Rowell, Rainbow");
INSERT INTO authors (name) values ("Zachary, G. Pascal");
INSERT INTO authors (name) values ("Haigh, Thomas");
INSERT INTO authors (name) values ("Burgess, Matthew");
INSERT INTO authors (name) values ("Madigan, Tim");
INSERT INTO authors (name) values ("Cartwright, Nancy");
INSERT INTO authors (name) values ("Fadiman, Anne");
INSERT INTO authors (name) values ("Sigmund, Karl");
INSERT INTO authors (name) values ("Bennett, Michael I.");
INSERT INTO authors (name) values ("Costas, Bob");
INSERT INTO authors (name) values ("Pei, Lowry");
INSERT INTO authors (name) values ("Rowell, Rainbow");
INSERT INTO authors (name) values ("Groff, Lauren");
INSERT INTO authors (name) values ("Perry, Paul");
INSERT INTO authors (name) values ("Wexler, Laura");
INSERT INTO authors (name) values ("Finch, Ava");
INSERT INTO authors (name) values ("Breathed, Berkeley");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Richman, Alan");
INSERT INTO authors (name) values ("Poundstone, William");
INSERT INTO authors (name) values ("Eco, Umberto");
INSERT INTO authors (name) values ("Goodman, Richard");
INSERT INTO authors (name) values ("Munro, Alice");
INSERT INTO authors (name) values ("Eisenstadt, Jill");
INSERT INTO authors (name) values ("Collins, Andrew");
INSERT INTO authors (name) values ("Greaney, Mark");
INSERT INTO authors (name) values ("Hornby, Nick");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Sandford, John");
INSERT INTO authors (name) values ("Coupland, Douglas");
INSERT INTO authors (name) values ("Childress, Mark");
INSERT INTO authors (name) values ("Davies, Anna");
INSERT INTO authors (name) values ("Hitchens, Christopher");
INSERT INTO authors (name) values ("Phillips, Marie");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Wainer, Howard");
INSERT INTO authors (name) values ("Harris, Charlaine");
INSERT INTO authors (name) values ("Denby, David");
INSERT INTO authors (name) values ("Norris, Mary");
INSERT INTO authors (name) values ("Gretzky, Wayne");
INSERT INTO authors (name) values ("Kirino, Natsuo");
INSERT INTO authors (name) values ("Bowden, Mark");
INSERT INTO authors (name) values ("Levy, Steven");
INSERT INTO authors (name) values ("Smith, Bob");
INSERT INTO authors (name) values ("Cahn, Steven M.");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Rowling, J.K.");
INSERT INTO authors (name) values ("Rowling, J.K.");
INSERT INTO authors (name) values ("Combs, Zach");
INSERT INTO authors (name) values ("Niffenegger, Audrey");
INSERT INTO authors (name) values ("Fearnley, James");
INSERT INTO authors (name) values ("Zapf, Hermann");
INSERT INTO authors (name) values ("Vance, J.D.");
INSERT INTO authors (name) values ("Hitchens, Christopher");
INSERT INTO authors (name) values ("Vollman, Rob");
INSERT INTO authors (name) values ("Lawhead, Stephen R.");
INSERT INTO authors (name) values ("Hely, Steve");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("DeJean, Joan");
INSERT INTO authors (name) values ("Franzen, Jonathan");
INSERT INTO authors (name) values ("Moran, Caitlin");
INSERT INTO authors (name) values ("Watsky, George");
INSERT INTO authors (name) values ("Smith, Dean O.");
INSERT INTO authors (name) values ("Bascomb, Neal");
INSERT INTO authors (name) values ("Barr, Nevada");
INSERT INTO authors (name) values ("Edison, Mike");
INSERT INTO authors (name) values ("Doyle, Larry");
INSERT INTO authors (name) values ("Mendelsohn, Jane");
INSERT INTO authors (name) values ("Klosterman, Chuck");
INSERT INTO authors (name) values ("Duncan, Glen");
INSERT INTO authors (name) values ("Barres, Pamela Des");
INSERT INTO authors (name) values ("Irving, John");
INSERT INTO authors (name) values ("Silver, Mitch");
INSERT INTO authors (name) values ("Tosches, Nick");
INSERT INTO authors (name) values ("French, Tana");
INSERT INTO authors (name) values ("Brown, Dan");
INSERT INTO authors (name) values ("Simpson, Charles M., III");
INSERT INTO authors (name) values ("Murray, Scott");
INSERT INTO authors (name) values ("Leander Kahney");
INSERT INTO authors (name) values ("Farber, Daniel A.");
INSERT INTO authors (name) values ("Hornby, Nick");
INSERT INTO authors (name) values ("Smith, Patti");
INSERT INTO authors (name) values ("Stevenson, Bryan");
INSERT INTO authors (name) values ("Garfield, Simon");
INSERT INTO authors (name) values ("Porter, Theodore M.");
INSERT INTO authors (name) values ("Salwey, Kenny");
INSERT INTO authors (name) values ("Poulsen, Kevin");
INSERT INTO authors (name) values ("Stradal, J. Ryan");
INSERT INTO authors (name) values ("Prior, Lily");
INSERT INTO authors (name) values ("Jahren, Hope");
INSERT INTO authors (name) values ("Moore, Christopher");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Weisberger, Lauren");
INSERT INTO authors (name) values ("Greathead, Kate");
INSERT INTO authors (name) values ("Davis, Nuel Pharr");
INSERT INTO authors (name) values ("Lerner, Ben");
INSERT INTO authors (name) values ("Muir, Kate");
INSERT INTO authors (name) values ("Greer, Andrew Sean");
INSERT INTO authors (name) values ("Mitchell, Richard");
INSERT INTO authors (name) values ("DeRogatis, Jim");
INSERT INTO authors (name) values ("Martinez, Elizabeth");
INSERT INTO authors (name) values ("Pickering, Samuel F., Jr.");
INSERT INTO authors (name) values ("Hitchens, Christopher");
INSERT INTO authors (name) values ("Barry, Max");
INSERT INTO authors (name) values ("Slonimsky, Nicolas");
INSERT INTO authors (name) values ("Martel, Yann");
INSERT INTO authors (name) values ("Moore, Lorrie");
INSERT INTO authors (name) values ("Saunders, George");
INSERT INTO authors (name) values ("Grossman, David");
INSERT INTO authors (name) values ("Karr, Mary");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Rich, Nathaniel");
INSERT INTO authors (name) values ("Beattie, Ann");
INSERT INTO authors (name) values ("Miralles, Francesc");
INSERT INTO authors (name) values ("Horan, Nancy");
INSERT INTO authors (name) values ("Emerson, Gloria");
INSERT INTO authors (name) values ("Amis, Kingsley");
INSERT INTO authors (name) values ("Henderson, Charles");
INSERT INTO authors (name) values ("Berg, A. Scott");
INSERT INTO authors (name) values ("de Hamel, Christopher");
INSERT INTO authors (name) values ("Vapnyar, Lara");
INSERT INTO authors (name) values ("Crichton, Michael");
INSERT INTO authors (name) values ("Sullivan, Matthew J.");
INSERT INTO authors (name) values ("Higginbotham, Adam");
INSERT INTO authors (name) values ("Nesbo, Jo");
INSERT INTO authors (name) values ("Riggs, Ransom");
INSERT INTO authors (name) values ("Coupland, Douglas");
INSERT INTO authors (name) values ("Collins, Suzanne");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Smiley, Jane");
INSERT INTO authors (name) values ("Hornby, Nick");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Arnold, David");
INSERT INTO authors (name) values ("Zlozower, Neil");
INSERT INTO authors (name) values ("Sloan, Robin");
INSERT INTO authors (name) values ("Trenerry, Walter N.");
INSERT INTO authors (name) values ("Kading, Greg");
INSERT INTO authors (name) values ("Bakopoulos, Dean");
INSERT INTO authors (name) values ("Adler, Steven");
INSERT INTO authors (name) values ("Black, Michael Ian");
INSERT INTO authors (name) values ("Ackerley, J.R.");
INSERT INTO authors (name) values ("Clash, Kevin");
INSERT INTO authors (name) values ("Strout, Elizabeth");
INSERT INTO authors (name) values ("Pouillon, Nora");
INSERT INTO authors (name) values ("Williams, Ted");
INSERT INTO authors (name) values ("Blatt, Ben");
INSERT INTO authors (name) values ("Chase, Owen");
INSERT INTO authors (name) values ("Pearson, Dan");
INSERT INTO authors (name) values ("Neruda, Pablo");
INSERT INTO authors (name) values ("Lindquist, Mark");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Pessl, Marisha");
INSERT INTO authors (name) values ("Perrotta, Tom");
INSERT INTO authors (name) values ("Lehrer, Jim");
INSERT INTO authors (name) values ("McCarthy, Cormac");
INSERT INTO authors (name) values ("Russo, Richard");
INSERT INTO authors (name) values ("Gaiman, Neil");
INSERT INTO authors (name) values ("Dunham, Lena");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Halberstam, David");
INSERT INTO authors (name) values ("Wolff, Tobias");
INSERT INTO authors (name) values ("Strout, Elizabeth");
INSERT INTO authors (name) values ("Hendel, Richard");
INSERT INTO authors (name) values ("McEwan, Ian");
INSERT INTO authors (name) values ("Mosteller, Frederick");
INSERT INTO authors (name) values ("Thucydides, Thucydides");
INSERT INTO authors (name) values ("Barzun, Jacques");
INSERT INTO authors (name) values ("Mitchell, Bob");
INSERT INTO authors (name) values ("Littman, Jonathan");
INSERT INTO authors (name) values ("Erwig, Martin");
INSERT INTO authors (name) values ("Bushnell, Candace");
INSERT INTO authors (name) values ("Childress, Mark");
INSERT INTO authors (name) values ("Child, Lee");
INSERT INTO authors (name) values ("Brown, Dan");
INSERT INTO authors (name) values ("Willis, Ellen");
INSERT INTO authors (name) values ("Nance, John J.");
INSERT INTO authors (name) values ("Basbanes, Nicholas A.");
INSERT INTO authors (name) values ("Child, Lee");
INSERT INTO authors (name) values ("Goldman, Sheldon");
INSERT INTO authors (name) values ("Crichton, Michael");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Heller, Ted");
INSERT INTO authors (name) values ("Pearson, T.R.");
INSERT INTO authors (name) values ("Slater, Robert");
INSERT INTO authors (name) values ("Moore, Christopher");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Godwin, Gail");
INSERT INTO authors (name) values ("Franzen, Jonathan");
INSERT INTO authors (name) values ("Lehrer, Jim");
INSERT INTO authors (name) values ("Douglas, Scott");
INSERT INTO authors (name) values ("Hartnett, Annie");
INSERT INTO authors (name) values ("Ro, Ronin");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Christensen, Ray");
INSERT INTO authors (name) values ("Nafisi, Azar");
INSERT INTO authors (name) values ("Cline, Ernest");
INSERT INTO authors (name) values ("Stephenson, Neal");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Matton, Sylvie");
INSERT INTO authors (name) values ("Cameron, W. Bruce");
INSERT INTO authors (name) values ("Vance, Lee");
INSERT INTO authors (name) values ("Weisberger, Lauren");
INSERT INTO authors (name) values ("Bowden, Mark");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Kennedy, Dan");
INSERT INTO authors (name) values ("Sittenfeld, Curtis");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Marcinko, Richard");
INSERT INTO authors (name) values ("Draper, Robert");
INSERT INTO authors (name) values ("Chamberlain, Marisha");
INSERT INTO authors (name) values ("Huneven, Michelle");
INSERT INTO authors (name) values ("Steinberg, Avi");
INSERT INTO authors (name) values ("Lear, Chris");
INSERT INTO authors (name) values ("Lindquist, Mark");
INSERT INTO authors (name) values ("Hoover, Paul");
INSERT INTO authors (name) values ("Thayer, Steve");
INSERT INTO authors (name) values ("Moore, Christopher Paul");
INSERT INTO authors (name) values ("McEwan, Ian");
INSERT INTO authors (name) values ("Charleson, Susannah");
INSERT INTO authors (name) values ("Wasdin, Howard E.");
INSERT INTO authors (name) values ("Wasdin, Howard E.");
INSERT INTO authors (name) values ("Adams, David");
INSERT INTO authors (name) values ("Thorne, John");
INSERT INTO authors (name) values ("Perkins, Tom");
INSERT INTO authors (name) values ("Butler, Nickolas");
INSERT INTO authors (name) values ("Costello, Mark");
INSERT INTO authors (name) values ("Phillips, Gary L.");
INSERT INTO authors (name) values ("Hornby, Nick");
INSERT INTO authors (name) values ("Carroll, Jonathan");
INSERT INTO authors (name) values ("Kaminer, Wendy");
INSERT INTO authors (name) values ("Marson, Bonnie");
INSERT INTO authors (name) values ("Wolitzer, Meg");
INSERT INTO authors (name) values ("Herron, Mick");
INSERT INTO authors (name) values ("McEwan, Ian");
INSERT INTO authors (name) values ("Hawke, Richard");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("O'Coughlin, Seamus");
INSERT INTO authors (name) values ("Shafrir, Doree");
INSERT INTO authors (name) values ("Royall, Richard");
INSERT INTO authors (name) values ("Rao, C. Radhakrishna");
INSERT INTO authors (name) values ("Reinhart, Alex");
INSERT INTO authors (name) values ("Reid, Harold");
INSERT INTO authors (name) values ("Habash, Gabe");
INSERT INTO authors (name) values ("Isaacson, Walter");
INSERT INTO authors (name) values ("Mallon, Thomas");
INSERT INTO authors (name) values ("Pears, Iain");
INSERT INTO authors (name) values ("Spiekermann, Erik");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Russo, Richard");
INSERT INTO authors (name) values ("Klein, Aaron J.");
INSERT INTO authors (name) values ("Garvey, Mark");
INSERT INTO authors (name) values ("Amis, Martin");
INSERT INTO authors (name) values ("Greaney, Mark");
INSERT INTO authors (name) values ("Buckley, Christopher");
INSERT INTO authors (name) values ("McEwan, Ian");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Sheffield, Rob");
INSERT INTO authors (name) values ("Nutting, Alissa");
INSERT INTO authors (name) values ("Chabon, Michael");
INSERT INTO authors (name) values ("Abramowitz, Andy");
INSERT INTO authors (name) values ("Russo, Richard");
INSERT INTO authors (name) values ("Quirk, Matthew");
INSERT INTO authors (name) values ("Dershowitz, Alan M.");
INSERT INTO authors (name) values ("Thornton, Tim");
INSERT INTO authors (name) values ("Lynds, Gayle");
INSERT INTO authors (name) values ("Holland, Travis");
INSERT INTO authors (name) values ("Shapiro, B.A.");
INSERT INTO authors (name) values ("Harbach, Chad");
INSERT INTO authors (name) values ("Burkle-Young, Francis A.");
INSERT INTO authors (name) values ("Charney, Noah");
INSERT INTO authors (name) values ("Aczel, Amir D.");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Koppel, Lily");
INSERT INTO authors (name) values ("Delury, Jane");
INSERT INTO authors (name) values ("Lowry, Elizabeth");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Koff, Clea");
INSERT INTO authors (name) values ("Connolly, John");
INSERT INTO authors (name) values ("Sagal, Peter");
INSERT INTO authors (name) values ("Pearl, Judea");
INSERT INTO authors (name) values ("Dunning, John");
INSERT INTO authors (name) values ("Colgan, Jenny");
INSERT INTO authors (name) values ("Dornstein, Ken");
INSERT INTO authors (name) values ("Brown, Daniel James");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Strout, Elizabeth");
INSERT INTO authors (name) values ("Watson, Peter");
INSERT INTO authors (name) values ("Ludlum, Robert");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Eisinger, Jesse");
INSERT INTO authors (name) values ("Central Intelligence Agency (C.I.A.)");
INSERT INTO authors (name) values ("Reichert, Amy E.");
INSERT INTO authors (name) values ("Goldstine, Herman H.");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Stoll, Clifford");
INSERT INTO authors (name) values ("Haddon, Mark");
INSERT INTO authors (name) values ("Walker, Martin");
INSERT INTO authors (name) values ("Sherwood, Ben");
INSERT INTO authors (name) values ("Manchester, William");
INSERT INTO authors (name) values ("Brooks, Frederick P., Jr.");
INSERT INTO authors (name) values ("Zerby, Chuck");
INSERT INTO authors (name) values ("Iles, Greg");
INSERT INTO authors (name) values ("Higashino, Keigo");
INSERT INTO authors (name) values ("Bauby, Jean-Dominique");
INSERT INTO authors (name) values ("Mlodinow, Leonard");
INSERT INTO authors (name) values ("Barbery, Muriel");
INSERT INTO authors (name) values ("Strunk, William, Jr.");
INSERT INTO authors (name) values ("Fforde, Jasper");
INSERT INTO authors (name) values ("Walter, Jess");
INSERT INTO authors (name) values ("Neville, Katherine");
INSERT INTO authors (name) values ("Faber, Michel");
INSERT INTO authors (name) values ("Dave, Laura");
INSERT INTO authors (name) values ("Iles, Greg");
INSERT INTO authors (name) values ("Littman, Jonathan");
INSERT INTO authors (name) values ("Dryden, Ken");
INSERT INTO authors (name) values ("Lagercrantz, David");
INSERT INTO authors (name) values ("Larsson, Stieg");
INSERT INTO authors (name) values ("King, Stephen");
INSERT INTO authors (name) values ("Larsson, Stieg");
INSERT INTO authors (name) values ("Zaslow, Jeffrey");
INSERT INTO authors (name) values ("Kenner, Julie");
INSERT INTO authors (name) values ("Kyle, Aryn");
INSERT INTO authors (name) values ("Pullman, Philip");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Roth, Philip");
INSERT INTO authors (name) values ("Deck, Jeff");
INSERT INTO authors (name) values ("Thompson, Jean");
INSERT INTO authors (name) values ("Morais, Richard C.");
INSERT INTO authors (name) values ("Collins, Suzanne");
INSERT INTO authors (name) values ("Ludlum, Robert");
INSERT INTO authors (name) values ("Skloot, Rebecca");
INSERT INTO authors (name) values ("Rachman, Tom");
INSERT INTO authors (name) values ("Rothschild, Hannah Mary");
INSERT INTO authors (name) values ("Meltzer, Brad");
INSERT INTO authors (name) values ("McEwan, Ian");
INSERT INTO authors (name) values ("Wolitzer, Meg");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Ludlum, Robert");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Lindquist, Mark");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Jacobs, A.J.");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Pearl, Matthew");
INSERT INTO authors (name) values ("Pearl, Matthew");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("McInerney, Jay");
INSERT INTO authors (name) values ("Conklin, Tara");
INSERT INTO authors (name) values ("Goldman, Ari L.");
INSERT INTO authors (name) values ("Larkin, Patrick");
INSERT INTO authors (name) values ("Perrotta, Tom");
INSERT INTO authors (name) values ("French, Tana");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("George, Nina");
INSERT INTO authors (name) values ("Udall, Brady");
INSERT INTO authors (name) values ("Moore, Christopher");
INSERT INTO authors (name) values ("Grossman, Lev");
INSERT INTO authors (name) values ("Olver, Robert");
INSERT INTO authors (name) values ("Sherwood, Ben");
INSERT INTO authors (name) values ("Mayle, Peter");
INSERT INTO authors (name) values ("Bukowski, Charles");
INSERT INTO authors (name) values ("Cameron, W. Bruce");
INSERT INTO authors (name) values ("Lustbader, Eric");
INSERT INTO authors (name) values ("Lewis, Chad");
INSERT INTO authors (name) values ("Shapiro, B.A.");
INSERT INTO authors (name) values ("Hall, Barbara");
INSERT INTO authors (name) values ("Chabon, Michael");
INSERT INTO authors (name) values ("Klein, Joe");
INSERT INTO authors (name) values ("Toobin, Jeffrey");
INSERT INTO authors (name) values ("Lustbader, Eric");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Moore, Wes");
INSERT INTO authors (name) values ("Ludlum, Robert");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Coren, Stanley");
INSERT INTO authors (name) values ("Michell, Tom");
INSERT INTO authors (name) values ("Bascomb, Neal");
INSERT INTO authors (name) values ("Wolitzer, Meg");
INSERT INTO authors (name) values ("Amis, Martin");
INSERT INTO authors (name) values ("Priest, Christopher");
INSERT INTO authors (name) values ("Winchester, Simon");
INSERT INTO authors (name) values ("Ronson, Jon");
INSERT INTO authors (name) values ("Feinstein, John");
INSERT INTO authors (name) values ("Iles, Greg");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Buckley, William F., Jr.");
INSERT INTO authors (name) values ("Rose, Augustus");
INSERT INTO authors (name) values ("Groth, Janet");
INSERT INTO authors (name) values ("Haddon, Mark");
INSERT INTO authors (name) values ("Bailey, Frankie Y.");
INSERT INTO authors (name) values ("Nesbø, Jo");
INSERT INTO authors (name) values ("Bryant, Jen");
INSERT INTO authors (name) values ("Rachman, Tom");
INSERT INTO authors (name) values ("Oates, Joyce Carol");
INSERT INTO authors (name) values ("Ridgway, Bee");
INSERT INTO authors (name) values ("McCarthy, Cormac");
INSERT INTO authors (name) values ("Rubenstein, Bruce");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Simsion, Graeme");
INSERT INTO authors (name) values ("Simsion, Graeme");
INSERT INTO authors (name) values ("Kirshenbaum, Sheril");
INSERT INTO authors (name) values ("Dyson, Freeman");
INSERT INTO authors (name) values ("Tartt, Donna");
INSERT INTO authors (name) values ("Barnes, Julian");
INSERT INTO authors (name) values ("Povey, Jeff");
INSERT INTO authors (name) values ("Stigler, Stephen M.");
INSERT INTO authors (name) values ("Fisher, Helen");
INSERT INTO authors (name) values ("Schumacher, Julie");
INSERT INTO authors (name) values ("Bowen, William G.");
INSERT INTO authors (name) values ("Moore, Graham");
INSERT INTO authors (name) values ("Reverte, Arturo Perez");
INSERT INTO authors (name) values ("Silver, Nate");
INSERT INTO authors (name) values ("Riker, H. Jay");
INSERT INTO authors (name) values ("Riker, H. Jay");
INSERT INTO authors (name) values ("Weisberger, Lauren");
INSERT INTO authors (name) values ("Brodrick, William");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Dickey, Christopher");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Rice, Christopher");
INSERT INTO authors (name) values ("Nesbo, Jo");
INSERT INTO authors (name) values ("Lehrer, Jim");
INSERT INTO authors (name) values ("Hassler, Jon");
INSERT INTO authors (name) values ("King, Stephen");
INSERT INTO authors (name) values ("Zevin, Gabrielle");
INSERT INTO authors (name) values ("Berg, Elizabeth");
INSERT INTO authors (name) values ("Hall, Tom T.");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Ford, Robert");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Hinton, Anthony Ray");
INSERT INTO authors (name) values ("Wiesenthal, Simon");
INSERT INTO authors (name) values ("Murphy, Austin");
INSERT INTO authors (name) values ("Pearl, Matthew");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Barker, Clive");
INSERT INTO authors (name) values ("Padua, Sydney");
INSERT INTO authors (name) values ("Niffenegger, Audrey");
INSERT INTO authors (name) values ("Stuart, Julia");
INSERT INTO authors (name) values ("Dicker, Joel");
INSERT INTO authors (name) values ("Marra, Anthony");
INSERT INTO authors (name) values ("Wolitzer, Meg");
INSERT INTO authors (name) values ("Lewis, Michael");
INSERT INTO authors (name) values ("Coover, Robert");
INSERT INTO authors (name) values ("Joyce, Rachel");
INSERT INTO authors (name) values ("Ferris, Joshua");
INSERT INTO authors (name) values ("Mayle, Peter");
INSERT INTO authors (name) values ("Thayer, Steve");
INSERT INTO authors (name) values ("Olsson, Karen");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Barron, Stephanie");
INSERT INTO authors (name) values ("Lehrer, Jim");
INSERT INTO authors (name) values ("Marwood, Alex");
INSERT INTO authors (name) values ("Hanagarne, Josh");
INSERT INTO authors (name) values ("Didion, Joan");
INSERT INTO authors (name) values ("Miller, Andy");
INSERT INTO authors (name) values ("Ferris, Joshua");
INSERT INTO authors (name) values ("Grisham, John");
INSERT INTO authors (name) values ("Knuth, Donald Ervin");
INSERT INTO authors (name) values ("Lodge, David");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Ponicsan, Darryl");
INSERT INTO authors (name) values ("Lehrer, Jim");
INSERT INTO authors (name) values ("Yallop, David A.");
INSERT INTO authors (name) values ("Bushnell, Candace");
INSERT INTO authors (name) values ("Russo, Richard");
INSERT INTO authors (name) values ("Levine, Sara");
INSERT INTO authors (name) values ("Godin, Seth");
INSERT INTO authors (name) values ("Geras, Adele");
INSERT INTO authors (name) values ("Greaney, Mark");
INSERT INTO authors (name) values ("Irving, John");
INSERT INTO authors (name) values ("Sheffield, Rob");
INSERT INTO authors (name) values ("Iles, Greg");
INSERT INTO authors (name) values ("Leighton, Ralph");
INSERT INTO authors (name) values ("Anderson, Laurie Halse");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Silvis, Randall");
INSERT INTO authors (name) values ("Goudy, Frederic W.");
INSERT INTO authors (name) values ("Blackwood, Grant");
INSERT INTO authors (name) values ("Dienes, Zoltan");
INSERT INTO authors (name) values ("Wainer, Howard");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Nicholls, David");
INSERT INTO authors (name) values ("Mead, Richelle");
INSERT INTO authors (name) values ("Lester, Paul Martin");
INSERT INTO authors (name) values ("Markoe, Merrill");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Olson, Parmy");
INSERT INTO authors (name) values ("O'Neil, Cathy");
INSERT INTO authors (name) values ("Collins, Cyn");
INSERT INTO authors (name) values ("Sykes, Tom");
INSERT INTO authors (name) values ("Garfunkel, Art");
INSERT INTO authors (name) values ("Simon, James F.");
INSERT INTO authors (name) values ("Bain, Ken");
INSERT INTO authors (name) values ("Markoff, John");
INSERT INTO authors (name) values ("Jarvis, Jeff");
INSERT INTO authors (name) values ("Forster, E.M.");
INSERT INTO authors (name) values ("Buffett, Jimmy");
INSERT INTO authors (name) values ("Lustbader, Eric");
INSERT INTO authors (name) values ("Curran, Colleen");
INSERT INTO authors (name) values ("Sedaris, Amy");
INSERT INTO authors (name) values ("Weisberg, Herbert I.");
INSERT INTO authors (name) values ("Clancy, Tom");
INSERT INTO authors (name) values ("Chabon, Michael");
INSERT INTO authors (name) values ("Stace, Wesley");
INSERT INTO authors (name) values ("Howey, Hugh");
INSERT INTO authors (name) values ("Stamper, Kory");
INSERT INTO authors (name) values ("Bowden, Mark");
INSERT INTO authors (name) values ("Child, Lee");
INSERT INTO authors (name) values ("Welk, Lawrence");
INSERT INTO authors (name) values ("Deaver, Jeffery");
INSERT INTO authors (name) values ("Bernheimer, Kate");
INSERT INTO authors (name) values ("Amis, Martin");
INSERT INTO authors (name) values ("Ziegesar, Cecily von");
INSERT INTO authors (name) values ("Moore, Christopher");
