INSERT INTO book(name, author_id, genre_id, year) values ("13 1/2",199,14,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Secret Diary of Hendrik Groen, 83 1/2 Years Old",2,14,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("18 and Life on Skid Row",3,4,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("A Choice of Weapons",4,14,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("A Civil War",520,6,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("A Clash of Kings ",24,7,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("A Dance with Dragons",24,6,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("A Degree of Mastery",8,8,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("A Discovery of Witches",9,14,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("A Fan's Notes",10,6,1968);
INSERT INTO book(name, author_id, genre_id, year) values ("A Feast for Crows",24,9,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("A Fool and His Monet",12,12,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("A Game of Thrones",24,11,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("A Gathering of Old Men",14,14,1983);
INSERT INTO book(name, author_id, genre_id, year) values ("A Good Life",15,5,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("A March to Madness",520,12,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("A Mind at Play",17,13,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("A Multitude of Sins",18,9,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("A Passion to Win",19,10,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("A Question of Attraction",621,8,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("A Short History of Tractors in Ukrainian",21,11,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("A Skeptic's Guide to Writers' Houses",22,14,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("A Spot of Bother",526,6,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("A Storm of Swords",24,14,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("A Stroke of Midnight",25,8,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("A Three Dog Life",26,10,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("A Time to Kill",596,1,1989);
INSERT INTO book(name, author_id, genre_id, year) values ("A Velocity of Being",28,6,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("A Visit from the Goon Squad",29,8,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("A Wanted Man",647,9,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("A Week on the Concord and Merrimac Rivers",31,13,1849);
INSERT INTO book(name, author_id, genre_id, year) values ("A Wolverine Is Eating My Leg",32,7,1989);
INSERT INTO book(name, author_id, genre_id, year) values ("Abraham Lincoln",33,1,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Academic Duty",34,1,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Academy X",35,13,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Against All Enemies",641,4,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Aleister Crowley",37,5,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("Algorithms to Live By",38,7,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("All I Want is Everything",652,10,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("All the Sad Young Literary Men",40,6,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Always Looking",41,11,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("American Assassin",42,4,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("American Gods",291,7,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Amy and Isabelle",423,8,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("An Accidental Statistician",45,14,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("And Yet ...",237,1,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Angelology",48,6,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Angelopolis",48,5,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Any Girl Who Loves The Beatles Is Bound To Break Your Heart",49,13,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Anything Is Possible",423,8,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Apathy for the Devil",51,8,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Archimedes Codex",52,10,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Are You There, Vodka? It's Me, Chelsea",53,8,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Armageddon in Retrospect",54,11,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("At Paradise Gate",264,11,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("At Random",56,11,1977);
INSERT INTO book(name, author_id, genre_id, year) values ("Atonement",472,13,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Attachments",145,6,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Bacchus & Me",484,7,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Back in the World",295,7,1985);
INSERT INTO book(name, author_id, genre_id, year) values ("Bad Dog",61,3,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Bad Dogs Have More Fun",62,5,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Bag Men",63,7,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Baseball Hacks",64,13,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Battle Cry of Freedom",65,11,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Beatrice and Virgil",240,3,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Between a Heart and a Rock Place",67,2,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Between You & Me",173,8,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Big Little Lies",69,11,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Bird by Bird",70,11,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("Blades of Glory",71,11,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Blind Submission",72,10,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Blood Memory",611,7,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Blood, Bones, and Butter",74,4,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Bonk",75,6,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Books",76,3,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Bridge of Sighs",604,2,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Bright Shark",78,5,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("Bright, Precious Days",484,11,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Brightness Falls",484,4,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("By the Book",81,7,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Calculating God",82,1,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Caldecott and Co.",83,1,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Calico Joe",596,7,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Call Me Puke",85,12,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Cassette From My Ex",86,13,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Catalyst",613,1,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Catching Fire",466,11,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Chasing Cezanne",585,2,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("Chloe Does Yale",90,5,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Chronicle of a Death Foretold",91,12,1981);
INSERT INTO book(name, author_id, genre_id, year) values ("City of Thieves",92,12,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Clothes, Clothes, Clothes. Music, Music, Music. Boys, Boys, Boys",93,5,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Code Girls",94,14,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Command Authority",641,10,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Confessions of an Economic Hit Man",96,8,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Connected Code",97,10,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Conversations on Writing Fiction",98,6,1994);
INSERT INTO book(name, author_id, genre_id, year) values ("Country Roads of Minnesota",99,11,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("Crisis in the Red Zone",100,7,2019);
INSERT INTO book(name, author_id, genre_id, year) values ("Crossing to Safety",101,5,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("Damaged",102,5,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Dancing Bear",103,3,1983);
INSERT INTO book(name, author_id, genre_id, year) values ("Dark Homecoming",637,5,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("Dead Air",105,13,1986);
INSERT INTO book(name, author_id, genre_id, year) values ("Dead Ever After",171,14,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Dead or Alive",641,10,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Dead Reckoning",171,14,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Deadlocked",171,3,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Dear Committee Members",545,5,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Dear Fahrenheit 451",111,8,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Dear Mr. Knightley",112,2,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Death and the Penguin",113,3,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("Design Literacy",114,3,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Dexter in the Dark",125,6,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Dexter's Final Cut",125,1,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Dictionaries",117,8,1984);
INSERT INTO book(name, author_id, genre_id, year) values ("Die Trying",647,3,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Digging for Dirt",119,13,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Digital Dice",120,9,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Distrust That Particular Flavor",121,11,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Dog on It",122,6,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Don't Rhyme For The Sake Of Riddlin'",123,8,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Don't You Forget About Me",124,14,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Double Dexter",125,14,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Down and Out in Paris and London",126,10,1933);
INSERT INTO book(name, author_id, genre_id, year) values ("Dr. Seuss & Mr. Geisel",127,7,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("Dragon Teeth",314,10,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Dreaming in Code",129,14,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Dreyer's English",130,13,2019);
INSERT INTO book(name, author_id, genre_id, year) values ("Duel in the Sun",131,14,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Eating Animals",132,5,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Edge",649,10,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Eleanor & Park",145,4,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Endless Frontier",135,6,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("ENIAC in Action",136,12,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Enormous Smallness",137,13,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Every Common Sight",138,13,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Evidence-Based Policy",139,4,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Ex Libris",140,6,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Exact Thinking in Demented Times",141,8,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("F*ck Feelings",142,14,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Fair Ball",143,10,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Family Resemblances",144,6,1986);
INSERT INTO book(name, author_id, genre_id, year) values ("Fangirl",145,11,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Fates and Furies",146,13,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Fear and Loathing",147,13,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("Fire In A Canebrake",148,9,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Fishing with RayAnne",149,11,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Flawed Dogs",150,10,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Ford County",596,12,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Forever's Team",520,10,1989);
INSERT INTO book(name, author_id, genre_id, year) values ("Fork It Over",153,6,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Fortune's Formula",154,12,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Foucault's Pendulum",155,13,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("French Dirt",156,4,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("Friend of My Youth",157,5,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("From Rockaway",158,4,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("From the Ashes of Angels",159,2,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Full Force and Effect",608,8,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Funny Girl",363,11,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Garden of Beasts",649,3,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Gathering Prey",163,11,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Generation X",261,11,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("Georgia Bottoms",306,5,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Glyph",166,9,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("God is Not Great",237,4,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Gods Behaving Badly",168,3,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Gossip Girl",652,6,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("Graphic Discovery",619,2,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Grave Secret",171,12,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Great Books",172,1,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Greek to Me",173,1,2019);
INSERT INTO book(name, author_id, genre_id, year) values ("Gretzky",174,13,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("Grotesque",175,13,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Guests of the Ayatollah",646,4,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Hackers",177,8,1984);
INSERT INTO book(name, author_id, genre_id, year) values ("Hamlet's Dresser",178,14,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("Happiness and Goodness",179,2,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Hard Courts",520,1,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("Harry Potter and the Goblet of Fire",182,11,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Harry Potter and the Prisoner of Azkaban",182,8,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("Headspin, Headshots & History",183,8,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Her Fearful Symmetry",576,12,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Here Comes Everybody",185,13,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Hermann Zapf and His Design Philosophy",186,10,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("Hillbilly Elegy",187,9,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Hitch-22",237,13,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Hockey Abstract Presents... Stat Shot",189,1,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Hood",190,13,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("How I Became a Famous Novelist",191,14,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("How it Ended",484,1,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("How Paris Became Paris",193,6,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("How to Be Alone",322,7,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("How to Build a Girl",195,7,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("How to Ruin Everything Deluxe",196,6,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("How University Budgets Work",197,2,2019);
INSERT INTO book(name, author_id, genre_id, year) values ("Hunting Eichmann",514,2,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Hunting Season",199,2,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("I Have Fun Everywhere I Go",200,2,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("I Love You, Beth Cooper",201,7,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("I Was Amelia Earhart",202,3,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("I Wear the Black Hat",203,2,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("I, Lucifer",204,4,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("I'm with the Band",205,10,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("In One Person",609,5,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("In Secret Service",207,13,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("In the Hand of Dante",208,7,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("In the Woods",489,14,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Inferno",308,9,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Inside The Green Berets",211,14,1983);
INSERT INTO book(name, author_id, genre_id, year) values ("Interactive Data Visualization for the Web",212,6,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Jony Ive",213,12,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Judgment Calls",214,10,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Juliet, Naked",363,9,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Just Kids",216,4,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Just Mercy",217,1,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Just My Type",218,11,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Karl Pearson",219,7,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Kenny Salwey's Tales of a River Rat",220,3,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Kingpin",221,2,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Kitchens of the Great Midwest",222,8,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("La Cucina",223,4,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Lab Girl",224,6,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Lamb",653,10,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Last Dance",520,10,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Last Night at Chateau Marmont",552,5,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Laura & Emma",228,8,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Lawrence and Oppenheimer",229,14,1968);
INSERT INTO book(name, author_id, genre_id, year) values ("Leaving the Atocha Station",230,13,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Left Bank",231,12,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Less",232,8,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Less Than Words Can Say",233,1,1979);
INSERT INTO book(name, author_id, genre_id, year) values ("Let it Blurt",234,14,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Letters from Mississippi",235,11,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Letters to a Teacher",236,4,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Letters to a Young Contrarian",237,13,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Lexicon",238,12,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Lexicon of Musical Invective",239,9,1953);
INSERT INTO book(name, author_id, genre_id, year) values ("Life of Pi",240,7,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Like Life",241,4,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("Lincoln in the Bardo",242,10,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Lion's Honey",243,13,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Lit",244,1,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Locked On",641,10,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Losing Earth",246,11,2020);
INSERT INTO book(name, author_id, genre_id, year) values ("Love Always",247,6,1985);
INSERT INTO book(name, author_id, genre_id, year) values ("Love in Lowercase",248,4,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Loving Frank",249,8,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Loving Graham Greene",250,5,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Lucky Jim",251,13,1953);
INSERT INTO book(name, author_id, genre_id, year) values ("Marine Sniper",252,7,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Max Perkins",253,11,1978);
INSERT INTO book(name, author_id, genre_id, year) values ("Meetings with Remarkable Manuscripts",254,13,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Memoirs of a Muse",255,1,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Micro",314,13,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Midnight at the Bright Ideas Bookstore",257,10,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Midnight in Chernobyl",258,5,2019);
INSERT INTO book(name, author_id, genre_id, year) values ("Midnight Sun",558,13,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Miss Peregrine's Home for Peculiar Children",260,13,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Miss Wyoming",261,9,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("Mockingjay",466,6,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Model Behavior",484,11,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("Moo",264,9,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("More Baths, Less Talking",363,6,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("More Twisted",649,5,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Mosquitoland",267,8,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Motley Crue",268,3,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Mr. Penumbra's 24-Hour Bookstore",269,6,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Murder in Minnesota",270,7,1962);
INSERT INTO book(name, author_id, genre_id, year) values ("Murder Rap",271,2,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("My American Unhappiness",272,12,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("My Appetite for Destruction",273,8,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("My Custom Van",274,10,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("My Dog Tulip",275,11,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("My Life as a Furry Red Monster",276,10,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("My Name Is Lucy Barton",423,6,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("My Organic Life",278,3,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("My Turn at Bat",279,8,1969);
INSERT INTO book(name, author_id, genre_id, year) values ("Nabokov's Favorite Word Is Mauve",280,8,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Narratives of the Wreck of the Whale-Ship Essex",281,5,1821);
INSERT INTO book(name, author_id, genre_id, year) values ("Natural Selection",282,9,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Neruda Memoirs",283,10,1974);
INSERT INTO book(name, author_id, genre_id, year) values ("Never Mind Nirvana",477,4,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Next Man Up",520,4,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Night Film",286,1,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Nine Inches",488,7,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("No Certain Rest",601,4,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("No Country for Old Men",533,7,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Nobody's Fool",604,7,1993);
INSERT INTO book(name, author_id, genre_id, year) values ("Norse Mythology",291,4,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Not That Kind of Girl",292,3,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Notorious",652,6,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("October, 1964",294,5,1994);
INSERT INTO book(name, author_id, genre_id, year) values ("Old School",295,1,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Olive Kitteridge",423,5,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("On Book Design",297,12,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("On Chesil Beach",472,5,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("On Equality of Educational Opportunity",299,5,1972);
INSERT INTO book(name, author_id, genre_id, year) values ("On Justice, Power and Human Nature",300,8,1993);
INSERT INTO book(name, author_id, genre_id, year) values ("On Writing, Editing, and Publishing",301,5,1971);
INSERT INTO book(name, author_id, genre_id, year) values ("Once Upon a Fastball",302,1,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Once Upon a Time in Computerland",451,6,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("Once Upon an Algorithm",304,4,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("One Fifth Avenue",603,7,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("One Mississippi",306,11,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("One Shot",647,5,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Origin",308,14,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Out of the Vinyl Deeps",309,1,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Pandora's Clock",310,12,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("Patience & Fortitude",311,7,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Personal",647,2,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Picking Federal Judges",313,12,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Pirate Latitudes",314,6,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Playing for Pizza",596,6,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Pocket Kings",316,13,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Polar",317,11,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("Portraits in Silicon",318,1,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("Practical Demonkeeping",653,4,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Praying for Sleep",649,11,1994);
INSERT INTO book(name, author_id, genre_id, year) values ("Publishing",321,7,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Purity",322,4,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Purple Dots",601,8,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("Quiet, Please",324,10,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Rabbit Cake",325,13,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Raising Hell",326,8,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Ransom",484,12,1985);
INSERT INTO book(name, author_id, genre_id, year) values ("Ray Christensen's Gopher Tales",328,6,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("Reading Lolita in Tehran",329,6,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Ready Player One",330,13,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Reamde",331,7,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Reckless",652,5,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Red Rabbit",641,4,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("Rembrandt's Whore",334,13,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Repo Madness",499,8,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Restitution",336,7,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Revenge Wears Prada",552,1,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Road Work",646,2,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Roadside Crosses",649,3,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Rock On",340,13,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Rodham",341,4,2020);
INSERT INTO book(name, author_id, genre_id, year) values ("Rogue Lawyer",596,7,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Rogue Warrior",343,4,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("Rolling Stone Magazine",344,10,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("Rose Variations",345,2,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Round Rock",346,7,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("Running the Books",347,8,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Running with the Buffaloes",348,7,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Sad Movies",477,11,1987);
INSERT INTO book(name, author_id, genre_id, year) values ("Saigon, Illinois",350,1,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Saint Mudd",586,11,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Santa and Pete",352,14,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("Saturday",472,6,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Scent of the Missing",354,2,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("SEAL Team Six",356,7,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("SEAL Team Six Outcasts",356,8,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Season of the Loon",357,7,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("Serious Pig",358,8,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("Sex and the Single Zillionaire",359,9,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Shotgun Lovesongs",360,7,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Signifying Rappers",361,4,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("Skate for Goal!",362,12,1982);
INSERT INTO book(name, author_id, genre_id, year) values ("Slam",363,7,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Sleeping in Flame",364,10,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Sleeping With Extra-Terrestrials",365,9,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("Sleeping with Schubert",366,2,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Sleepwalking",580,6,1982);
INSERT INTO book(name, author_id, genre_id, year) values ("Slow Horses",368,10,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Solar",472,8,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Speak of the Devil",370,6,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Speaking In Tongues",649,5,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("Squaw Valley Gold",372,6,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Startup",373,1,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Statistical Evidence",374,2,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Statistics And Truth",375,6,1989);
INSERT INTO book(name, author_id, genre_id, year) values ("Statistics Done Wrong",376,9,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Statler Bros. Random Memories",377,7,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Stephen Florida",378,2,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("Steve Jobs",379,10,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Stolen Words",380,6,1989);
INSERT INTO book(name, author_id, genre_id, year) values ("Stone's Fall",381,5,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Stop Stealing Sheep & Find Out How Type Works",382,5,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Story of My Life",484,9,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("Straight Man",604,11,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("Striking Back",385,10,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Stylized",386,14,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Success",651,12,1978);
INSERT INTO book(name, author_id, genre_id, year) values ("Support and Defend",608,1,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Supreme Courtship",389,1,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Sweet Tooth",472,3,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Sycamore Row",596,7,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Tales from Q School",520,1,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Talking to Girls About Duran Duran",610,12,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Tampa",394,1,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Telegraph Avenue",642,1,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Thank You, Goodnight",396,10,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("That Old Cape Magic",604,4,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The 500",398,4,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Advocate's Devil",399,14,1994);
INSERT INTO book(name, author_id, genre_id, year) values ("The Alternative Hero",400,14,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Altman Code",401,1,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Archivist's Story",402,3,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Art Forger",502,5,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Art of Fielding",404,14,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Art of the Footnote",405,6,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("The Art Thief",406,14,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Artist and the Mathematician",407,3,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("The Associate",596,1,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Astronaut Wives Club",409,2,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Balcony",410,5,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Bellini Madonna",411,4,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Bodies Left Behind",649,5,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Bone Woman",413,11,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Book of Lost Things",414,7,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Book of Vice",415,4,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Book of Why",416,11,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Bookman's Wake",417,6,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("The Bookshop on the Corner",418,3,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("The Boy Who Fell Out of the Sky",419,14,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("The Boys in the Boat",420,3,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Brethren",596,11,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("The Broker",596,5,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The Burgess Boys",423,5,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Caravaggio Conspiracy",424,7,1983);
INSERT INTO book(name, author_id, genre_id, year) values ("The Cassandra Compact",510,5,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Chamber",596,6,1994);
INSERT INTO book(name, author_id, genre_id, year) values ("The Chickenshit Club",427,1,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The CIA Document of Human Manipulation",428,3,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Coincidence of Coconut Cake",429,14,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Computer from Pascal to Von Neumann",430,13,1972);
INSERT INTO book(name, author_id, genre_id, year) values ("The Confession",596,5,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Cuckoo's Egg",432,8,1989);
INSERT INTO book(name, author_id, genre_id, year) values ("The Curious Incident of the Dog in the Night-Time",526,7,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Dark Vineyard",434,7,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Death and Life of Charlie St. Cloud",496,5,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Death of a President",436,12,1967);
INSERT INTO book(name, author_id, genre_id, year) values ("The Design of Design",437,8,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Devil's Details",438,11,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Devil's Punchbowl",611,5,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Devotion of Suspect X",440,11,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The Diving Bell and the Butterfly",441,9,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("The Drunkard's Walk",442,10,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Elegance of the Hedgehog",443,12,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Elements of Style",444,14,1918);
INSERT INTO book(name, author_id, genre_id, year) values ("The Eyre Affair",445,5,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Financial Lives of the Poets",446,6,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Fire",447,2,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Fire Gospel",448,3,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("The First Husband",449,3,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Footprints of God",611,14,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Fugitive Game",451,8,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("The Game",452,11,1983);
INSERT INTO book(name, author_id, genre_id, year) values ("The Girl in the Spider's Web",453,1,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Girl Who Kicked the Hornet's Nest",456,9,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Girl Who Loved Tom Gordon",561,7,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("The Girl with the Dragon Tattoo",456,6,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The Girls from Ames",457,1,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Givenchy Code",458,8,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The God of Animals",459,14,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Golden Compass",460,11,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("The Good Life",484,11,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("The Great American Novel",462,4,1973);
INSERT INTO book(name, author_id, genre_id, year) values ("The Great Typo Hunt",463,10,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Humanity Project",464,2,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Hundred-Foot Journey",465,2,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Hunger Games",466,7,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Icarus Agenda",510,5,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("The Immortal Life of Henrietta Lacks",468,10,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Imperfectionists",530,11,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Improbability of Love",470,2,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Inner Circle",471,6,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Innocent",472,5,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("The Interestings",580,4,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The It Girl",652,9,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The Janson Directive",510,8,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Kill Room",649,9,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The King of Methlehem",477,1,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The King of Torts",596,13,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Know-It-All",479,3,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Last Amateurs",520,8,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Last Bookaneer",571,7,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Last Dickens",571,5,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Last Juror",596,9,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Last of the Savages",484,12,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("The Last Romantics",485,11,2020);
INSERT INTO book(name, author_id, genre_id, year) values ("The Late Starters Orchestra",486,5,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("The Lazarus Vendetta",487,8,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Leftovers",488,9,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Likeness",489,5,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("The Litigators",596,4,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Little Paris Bookshop",491,9,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Lonely Polygamist",492,3,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Lust Lizard of Melancholy Cove",653,7,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("The Magicians",494,3,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Making Of Champions",495,14,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("The Man Who Ate the 747",496,1,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("The Marseille Caper",585,5,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Mathematics of the Breath and the Way",498,3,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Midnight Plan of the Repo Man",499,9,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("The Miko",637,11,1984);
INSERT INTO book(name, author_id, genre_id, year) values ("The Minnesota Road Guide to Gangster Hot Spots",501,6,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Muralist",502,13,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Music Teacher",503,2,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Mysteries of Pittsburgh",642,2,1988);
INSERT INTO book(name, author_id, genre_id, year) values ("The Natural",505,4,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Nine",506,9,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Ninja",637,10,1980);
INSERT INTO book(name, author_id, genre_id, year) values ("The October List",649,7,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Other Wes Moore",509,5,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Paris Option",510,4,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Partner",596,12,1997);
INSERT INTO book(name, author_id, genre_id, year) values ("The Pawprints of History",512,9,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Penguin Lessons",513,12,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Perfect Mile",514,12,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Position",580,12,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The Pregnant Widow",651,11,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Prestige",517,5,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("The Professor and the Madman",518,6,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("The Psychopath Test",519,12,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Punch",520,3,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Quiet Game",611,2,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("The Racketeer",596,13,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rake",523,13,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Readymade Thief",524,6,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Receptionist",525,3,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Red House",526,13,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Red Queen Dies",527,14,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Redbreast",528,13,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Right Word",529,13,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rise & Fall of Great Powers",530,11,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rise of Life on Earth",531,5,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("The River of No Return",532,9,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Road",533,1,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rockwell Heist",534,5,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rooster Bar",596,11,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rosie Effect",537,1,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Rosie Project",537,12,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Science of Kissing",538,12,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Scientist as Rebel ",539,13,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("The Secret History",540,14,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sense of an Ending",541,6,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Serial Killers Club",542,12,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("The Seven Pillars of Statistical Wisdom",543,7,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sex Contract",544,8,1982);
INSERT INTO book(name, author_id, genre_id, year) values ("The Shakespeare Requirement",545,10,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Shape of the River",546,2,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sherlockian",547,8,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Siege",548,1,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Signal and the Noise",549,3,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Silent Service: Los Angeles Class",551,14,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Silent Service: Virginia Class",551,11,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Singles Game",552,6,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sixth Lamentation",553,4,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Skin Collector ",649,14,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sleeper",555,10,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sleeping Doll",649,2,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Snow Garden",557,5,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Snowman",558,1,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Special Prisoner",601,1,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("The Staggerford Murders and Nancy Clancy's Nephew",560,9,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("The Stand",561,12,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("The Storied Life of A.J. Fikry",562,13,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("The Story of Arthur Truluv",563,3,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("The Storyteller's Nashville",564,11,1979);
INSERT INTO book(name, author_id, genre_id, year) values ("The Street Lawyer",596,9,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("The Student Conductor",566,14,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Summons",596,6,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sun Does Shine",568,7,2018);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sunflower",569,14,1998);
INSERT INTO book(name, author_id, genre_id, year) values ("The Sweet Season",570,6,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("The Technologists",571,13,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Teeth of the Tiger",641,11,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Testament",596,7,1999);
INSERT INTO book(name, author_id, genre_id, year) values ("The Thief of Always",574,12,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("The Thrilling Adventures of Lovelace and Babbage",575,9,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Time Traveler's Wife",576,1,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("The Tower, The Zoo, and The Tortoise",577,11,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Truth About the Harry Quebert Affair",578,7,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Tsar of Love and Techno",579,11,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("The Uncoupling",580,13,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("The Undoing Project",581,4,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("The Universal Baseball Association, Inc., J. Henry Waugh, Prop",582,12,1968);
INSERT INTO book(name, author_id, genre_id, year) values ("The Unlikely Pilgrimage of Harold Fry",583,1,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("The Unnamed",595,1,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("The Vintage Caper",585,7,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The Weatherman",586,11,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("The Weil Conjectures",587,12,2019);
INSERT INTO book(name, author_id, genre_id, year) values ("The Whistler",596,10,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("The White Garden",589,1,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("The White Widow",601,8,1996);
INSERT INTO book(name, author_id, genre_id, year) values ("The Wicked Girls",591,12,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The World's Strongest Librarian",592,14,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("The Year of Magical Thinking",593,12,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("The Year of Reading Dangerously",594,14,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Then We Came to the End",595,6,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Theodore Boone",596,11,2010);
INSERT INTO book(name, author_id, genre_id, year) values ("Things a Computer Scientist Rarely Talks About",597,14,2001);
INSERT INTO book(name, author_id, genre_id, year) values ("Thinks�",598,9,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("Threat Vector",641,3,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Tom Mix Died For Your Sins",600,9,1975);
INSERT INTO book(name, author_id, genre_id, year) values ("Top Down",601,1,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Tracking the Jackal",602,11,1993);
INSERT INTO book(name, author_id, genre_id, year) values ("Trading Up",603,1,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Trajectory",604,7,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Treasure Island!!!",605,14,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Tribes",606,9,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Troy",607,5,2000);
INSERT INTO book(name, author_id, genre_id, year) values ("True Faith and Allegiance",608,12,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("Trying to Save Piggy Sneed",609,12,1993);
INSERT INTO book(name, author_id, genre_id, year) values ("Turn Around Bright Eyes",610,12,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Turning Angel",611,5,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Tuva or Bust!",612,1,1991);
INSERT INTO book(name, author_id, genre_id, year) values ("Twisted",613,6,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Twisted",649,9,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("Two Days Gone",615,5,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Typologia",616,14,1976);
INSERT INTO book(name, author_id, genre_id, year) values ("Under Fire",617,6,2015);
INSERT INTO book(name, author_id, genre_id, year) values ("Understanding Psychology as a Science",618,13,2008);
INSERT INTO book(name, author_id, genre_id, year) values ("Uneducated Guesses",619,13,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Unforgettable",652,6,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Us",621,2,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Vampire Academy",622,12,2007);
INSERT INTO book(name, author_id, genre_id, year) values ("Visual Communication",623,14,1994);
INSERT INTO book(name, author_id, genre_id, year) values ("Walking in Circles Before Lying Down",624,2,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("Watchlist",649,7,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("We Are Anonymous",626,2,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Weapons of Math Destruction",627,2,2016);
INSERT INTO book(name, author_id, genre_id, year) values ("West Bank Boogie",628,2,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("What Did I Do Last Night?",629,7,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("What Is It All But Luminous",630,14,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("What Kind of Nation",631,1,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("What the Best College Teachers Do",632,8,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("What the Dormouse Said",633,7,2006);
INSERT INTO book(name, author_id, genre_id, year) values ("What Would Google Do?",634,11,2009);
INSERT INTO book(name, author_id, genre_id, year) values ("Where Angels Fear To Tread",635,4,1905);
INSERT INTO book(name, author_id, genre_id, year) values ("Where Is Joe Merchant?",636,6,1992);
INSERT INTO book(name, author_id, genre_id, year) values ("White Ninja",637,9,1990);
INSERT INTO book(name, author_id, genre_id, year) values ("Whores on the Hill",638,4,2005);
INSERT INTO book(name, author_id, genre_id, year) values ("Wigfield",639,13,2004);
INSERT INTO book(name, author_id, genre_id, year) values ("Willful Ignorance",640,9,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Without Remorse",641,8,1993);
INSERT INTO book(name, author_id, genre_id, year) values ("Wonder Boys",642,1,1995);
INSERT INTO book(name, author_id, genre_id, year) values ("Wonderkid",643,11,2014);
INSERT INTO book(name, author_id, genre_id, year) values ("Wool",644,7,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("Word by Word",645,12,2017);
INSERT INTO book(name, author_id, genre_id, year) values ("Worm",646,10,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Worth Dying For",647,10,2011);
INSERT INTO book(name, author_id, genre_id, year) values ("Wunnerful, Wunnerful!",648,11,1971);
INSERT INTO book(name, author_id, genre_id, year) values ("XO",649,12,2012);
INSERT INTO book(name, author_id, genre_id, year) values ("xo Orpheus",650,11,2013);
INSERT INTO book(name, author_id, genre_id, year) values ("Yellow Dog",651,9,2003);
INSERT INTO book(name, author_id, genre_id, year) values ("You Know You Love Me",652,2,2002);
INSERT INTO book(name, author_id, genre_id, year) values ("You Suck",653,10,2007);
