version: "3.9"
services:
  booking-api:
    build: .
  nginx:
    image: "nginx"
    volumes:
    - ./vhost.conf:/etc/nginx/conf.d/bookking-api.conf
    ports:
      - "8080:8080"
  mysql:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
